name: furdle
description: A word puzzle to guess the word in 6 attempts

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.3.7+11

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  cloud_firestore: ^6.0.1
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  http: ^1.3.0
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  logger: ^2.6.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Furdle.jpg"
flutter:
  uses-material-design: true
  assets:
    - assets/
