// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmGgV6nY5tm08N_z8XrcQALnMdvJ7XKOU',
    appId: '1:888112482915:web:40255c62b5e9114c7a0656',
    messagingSenderId: '888112482915',
    projectId: 'furdle',
    authDomain: 'furdle.firebaseapp.com',
    storageBucket: 'furdle.appspot.com',
    measurementId: 'G-FPVV8JLE80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUHkTO8B6ralAqDRJbisthJrbKPE2ktgI',
    appId: '1:888112482915:android:37672b049bad802e7a0656',
    messagingSenderId: '888112482915',
    projectId: 'furdle',
    storageBucket: 'furdle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwIznJhjd4vXGQskxOgBLVAsvgmO3UTHk',
    appId: '1:888112482915:ios:152e772dd190fb247a0656',
    messagingSenderId: '888112482915',
    projectId: 'furdle',
    storageBucket: 'furdle.appspot.com',
    iosClientId: '888112482915-l02ra6cp660cksfb0rc6cpptjck65cqn.apps.googleusercontent.com',
    iosBundleId: 'com.wml.furdle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwIznJhjd4vXGQskxOgBLVAsvgmO3UTHk',
    appId: '1:888112482915:ios:152e772dd190fb247a0656',
    messagingSenderId: '888112482915',
    projectId: 'furdle',
    storageBucket: 'furdle.appspot.com',
    iosClientId: '888112482915-l02ra6cp660cksfb0rc6cpptjck65cqn.apps.googleusercontent.com',
    iosBundleId: 'com.wml.furdle',
  );
}
